name: DO Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Copy files
        uses: appleboy/ssh-action@master
        env:
          DEPLOYPATH: "/var/www/nubeliquida.com/public_html/"
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          envs: DEPLOYPATH
          script: |
            cd repositories/nubeliquida
            git pull origin
            echo "Update repo"
            echo "$DEPLOYPATH"
            cp *.html $DEPLOYPATH
            cp sitemap_index.xml $DEPLOYPATH
            cp composer* $DEPLOYPATH
            cp .htaccess $DEPLOYPATH
            cp -R css/ $DEPLOYPATH
            cp -R fonts/ $DEPLOYPATH
            cp -R img/ $DEPLOYPATH
            cp -R js/ $DEPLOYPATH
            cp -R subscription/ $DEPLOYPATH
